# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               Mining Online Data for Early Identification of Unsafe Food Products
tagline:             ''
description:         'A Data Science for Social Good 2016 fellowship project.'
url:                 https://uwescience.github.io/DSSG2016-UnsafeFoods/
baseurl:             ''

# About/contact
# author:
#   name:
#   url:
#   email:

# Custom vars
version:             0.0.1
